# Generated by Django 6.0 on 2025-12-30 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('gambar', models.ImageField(upload_to='artikel/')),
                ('isi', models.TextField()),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('sub_judul', models.TextField(blank=True)),
                ('gambar', models.ImageField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KategoriProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KontakPesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pesan', models.TextField()),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=100)),
                ('icon', models.ImageField(help_text='Upload ikon SVG/PNG', upload_to='layanan/')),
                ('deskripsi_singkat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_apotek', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('alamat', models.TextField()),
                ('no_telepon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('deskripsi_footer', models.TextField(help_text='Teks singkat di footer')),
            ],
        ),
        migrations.CreateModel(
            name='TimApotek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('posisi', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='tim/')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=12)),
                ('gambar', models.ImageField(upload_to='produk/')),
                ('deskripsi', models.TextField()),
                ('is_unggulan', models.BooleanField(default=False, help_text='Centang jika ingin tampil di halaman depan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produk', to='api.kategoriproduk')),
            ],
        ),
    ]
